### ISSUE TITLE
TimeBandits::TimeConsumers::Database metrics missing

### ISSUE THREAD

**Issue by roccoblues** [skaes/time_bandits#12]
Hi,

not sure if it can really considered a bug, but at least it's unexpected behavior. I noticed that you have to call the `consumed()` method before `metrics()` otherwise the metrics are empty.

This doesn't work:

```
TimeBandits.reset
[ do DB queries ]
TimeBandits.metrics
```

This does:
```
TimeBandits.reset
[ do DB queries ]
TimeBandits::TimeConsumers::Database.instance.consumed
TimeBandits.metrics
```

I ran into that while writing a [logjam_agent](https://github.com/skaes/logjam_agent) middleware for [sidekiq](https://github.com/mperham/sidekiq). I suspect the `consumed()` method isn't called because the logging in `ActiveJob` is different.

For the record, here's the [middleware](https://gist.github.com/roccoblues/6846822c2c349465f446220a9772a2f3) I ended up with.

**Comment by skaes** [comment]
Yes, it's necessary to call consumed before calling metrics. Rails calls this before view rendering, so it can separate DB time before rendering from db time during rendering. It then subtracts the db time accumulated during rendering from the view time. Maybe one could get rid of this peculiarity by monkey patching differently.
