### ISSUE TITLE
Total time is not right

### ISSUE THREAD

**Issue by twang333** [skaes/time_bandits#8]
After I enabled this gem, my log is changed from 
"Completed 200 OK in 2795.5ms (Views: 2324.7ms | ActiveRecord: 422.2ms)"
To
"Completed 200 OK in 2.9ms (Views: 2361.964ms | ActiveRecord: 438.011ms(1638q,1047h))"

Apparently, 2.9 ms is not right.

FYI
$ rails -v
Rails 3.2.18
$ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

**Comment by skaes** [comment]
It's quite possible rails 3.2.x isn't properly supported anymore. I'll try to look int it over the weekend.

**Comment by pinglamb** [comment]
Seems 2.9ms is actually 2.9s, is it related to this commit?

https://github.com/skaes/time_bandits/commit/1fd2ff7d32ae33c833f7397469cfba26d513c4ba

**Comment by skaes** [comment]
It's along time since I ran any application with rails 3.2.x. It's possible that the code is wrong for Rails 3. I will check.
